services:
  db:
    container_name: openconnect-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: openconnect
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: openconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openconnect -d openconnect"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: openconnect-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_DSN: postgres://openconnect:1234@db:5432/openconnect?sslmode=disable
      SMTPPORT: ${SMTPPORT}
      SMTPHOST: ${SMTPHOST}
      SMTPUSERNAME: ${SMTPUSERNAME}
      SMTPPASS: ${SMTPPASS}
      SMTPSENDER: ${SMTPSENDER}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
